### PR TITLE
Fix size lookup when a flavor has been deleted

### PR DESCRIPTION
**Pull request by MoteHue**
An instance can be running with a flavor that has since been deleted. When this is the case, the Machines tab will crash with ``TypeError: t.size is null``.

Fix this by replacing ``null`` with an empty object.

### CODE REVIEW

**Review by mkjpryor — CHANGES_REQUESTED** [review]
@MoteHue

Nice work.

Can you have a crack at fixing this where it occurs in the platforms tab as well? We had a customer hit it today and it would be good to get it fixed.

**Comment by MoteHue** [comment]
There were a few places where the size is used in a K8s platform. I've move the existence check to inside MachineSizeLink to minimise the number of checks needed.

**Review by mkjpryor — CHANGES_REQUESTED** [review]
@MoteHue

Good idea to move the check into the `MachineSizeLink` component, but did you miss a file in your commit? I don't see the required changes to the `MachineSizeLink` component itself.

**Comment by MoteHue** [comment]
> @MoteHue
> 
> Good idea to move the check into the `MachineSizeLink` component, but did you miss a file in your commit? I don't see the required changes to the `MachineSizeLink` component itself.

I did miss this, added now :+1:

**Review by mkjpryor — APPROVED** [review]
LGTM

**Pull request merged**
